name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
  - cron: "0 7 * * *"

jobs:

  test-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Camel K
        uses: ./

      - name: Test
        shell: bash
        run: |
          kamel version

  test-default:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Camel K
        uses: ./
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Test
        shell: bash
        run: |
          kamel version

  test-with-custom-version:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        version:
        - v1.10.4
        - v1.12.1
        - v2.0.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Camel K
        with:
          version: ${{ matrix.version }}
        uses: ./

      - name: Test
        shell: bash
        run: |
          kamel version
